name: Build and Push mail_poller Docker image

env:
    REGISTRY: ghcr.io

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      
      
      - name: Build and push mail_poller image
        uses: docker/build-push-action@v5
        with:
          context: mail_poller
          file: .dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/moneytracker/mail_poller:latest 