name: Build and Push mail_poller Docker image

env:
    REGISTRY: ghcr.io

on:
  push:
    branches: [ main ]

jobs:
  build_mail_poller:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      
      - name: Build and push mail_poller image
        uses: docker/build-push-action@v5
        with:
          file: mail_poller/.dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/mail_poller:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}/mail_poller:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}/mail_poller:buildcache,mode=max
  
  build_llm_agent:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      
      - name: Build and push llm_agent image
        uses: docker/build-push-action@v5
        with:
          file: llm_agent/.dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/llm_agent:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}/llm_agent:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}/llm_agent:buildcache,mode=max
  
  build_money_bot:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      
      - name: Build and push money_bot image
        uses: docker/build-push-action@v5
        with:
          file: money_bot/.dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/money_bot:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}/money_bot:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}/money_bot:buildcache,mode=max